### ISSUE TITLE
Use context managers for file I/O

### ISSUE THREAD

**Issue by thatvideoshopguy** [LangTrans/LangTrans#17]
### Description
To ensure proper file handling and avoid potential issues, we should use context managers when working with files. This will automatically close files after use, preventing resource leaks.

### Example
In the `load_yaml()` function, replace `open(file).read()` with `with open(file) as f: f.read()`.

```bash
def load_yaml(file: str) -> dict[str, Any]:
...
    try:
        with open(file) as f:
            return load(f.read(), Loader=SafeLoader)
...
```

**Comment by B-R-P** [comment]
Solved in commit https://github.com/LangTrans/LangTrans/commit/4b228da18a12433c21ddeba8aced5a37b709c41c
