### ISSUE TITLE
Built-in regular expressions

### ISSUE THREAD

**Issue by B-R-P** [LangTrans/LangTrans#8]
What are the common or useful regular expressions?
For [builtin.yaml](https://github.com/LangTrans/LangTrans/blob/main/builtin.yaml).
**Note:** Add regex to match language constructs

**Comment by B-R-P** [comment]
Add some useful regular expression in [builtin.yaml](https://github.com/LangTrans/LangTrans/blob/main/builtin.yaml).

**Comment by AnkanHalder** [comment]
Do you have something particular in mind? I love the idea and would like to work on this. 
Can I work on it ? 

I start with the following:

Operators:
-  logical operators
- logical & arithmetic
- logical OR arithmetic

Data Type Match:

- Binary 
- Hexadecimal
- Octal
- alphanumeric without space or tabs
- alphanumeric with space/ tabs

Digit Match:

- Whole Numbers
- Decimal Numbers
- whole+Decimal
- Fraction
- Integer

Email Match

UserName Type Match - Alphanumeric but only  1 type of special character( _ )

Password Type Match

- Strong 
- Moderate
- Weak


Different Time Format Matches
HTML tag Type match

**Comment by B-R-P** [comment]
Thank you for working on it.
### Importance of Regex
Regular expressions are used to extract tokens from source code.
Simply, manipulating such tokens is overall working of LangTrans.

> Do you have something particular in mind? I love the idea and would like to work on this. Can I work on it ?

Regular expressions for extracting tokens that are common in source codes will be in `builtin.yaml`.
Adding such regular expression will be helpful for future use. Examples are present in that [file](https://github.com/LangTrans/LangTrans/blob/main/builtin.yaml).
> I start with the following:
> 
> Operators:
> 
> * logical operators
> * logical & arithmetic
> * logical OR arithmetic
> 
> Data Type Match:
> 
> * Binary
> * Hexadecimal
> * Octal
> * alphanumeric without space or tabs
> * alphanumeric with space/ tabs
> 
> Digit Match:
> 
> * Whole Numbers
> * Decimal Numbers
> * whole+Decimal
> * Fraction
> * Integer

These regular expressions become helpful.

> Email Match
> 
> UserName Type Match - Alphanumeric but only 1 type of special character( _ )
> 
> Password Type Match
> 
> * Strong
> * Moderate
> * Weak
> 
> Different Time Format Matches HTML tag Type match

These regular expressions are not necessary. Thus it need not be in builtins.

**Comment by LyBaoMinEmi** [comment]
Email validation: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
Phone number validation: ^\d{10}$|^\d{3}-\d{3}-\d{4}$|^\d{3}-\d{4}-\d{4}$
URL validation: ^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$
IP address validation: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
Date validation: ^(0[1-9]|1[0-2])\/(0[1-9]|1\d|2\d|3[01])\/(19|20)\d{2}$

**Comment by LyBaoMinEmi** [comment]
Add some useful regular expression in [builtin.yaml](https://github.com/LangTrans/LangTrans/blob/main/builtin.yaml).:
Time validation: ^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$
Alphabetic characters only: ^[a-zA-Z]+$
Alphanumeric characters only: ^[a-zA-Z0-9]+$
Numeric characters only: ^[0-9]+$
Password validation (minimum 8 characters, at least 1 uppercase and 1 lowercase letter, and 1 number): ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$

**Comment by meaviral17** [comment]
I learnt this topic this month. Let me try this one out

**Comment by meaviral17** [comment]
> I learnt this topic this month. Let me try this one out

Just sent my PR.

**Comment by umar052001** [comment]
Hello! I am interested in working on this issue and would like to request the assignment. I have experience with regular expressions and believe that I can contribute to this project. Could you please assign this issue to me? Thank you!

**Comment by siddarthpai** [comment]
hey can I work on this issue

**Comment by Neerpatel25** [comment]
Hey Can I work on this issue?

**Comment by GoofyBluff** [comment]
Would love to try this.

**Comment by B-R-P** [comment]
Anyone can submit their pull request if they understand the use of regular expressions in LangTrans.

**Comment by sanju50201** [comment]
Since no one is assigned, can i work on this?

**Comment by Aditi840** [comment]
Hello I'm Aditi, will you please check the pull request that I have created

**Comment by Aditi840** [comment]
@B-R-P will you please try to run test again on my updated builtin.yaml file.
